// Generated by gencpp from file pluto_camera_sense/frame.msg
// DO NOT EDIT!


#ifndef PLUTO_CAMERA_SENSE_MESSAGE_FRAME_H
#define PLUTO_CAMERA_SENSE_MESSAGE_FRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pluto_camera_sense
{
template <class ContainerAllocator>
struct frame_
{
  typedef frame_<ContainerAllocator> Type;

  frame_()
    : frameBuffer()
    , frameSize(0)
    , iframe(false)  {
    }
  frame_(const ContainerAllocator& _alloc)
    : frameBuffer(_alloc)
    , frameSize(0)
    , iframe(false)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _frameBuffer_type;
  _frameBuffer_type frameBuffer;

   typedef uint32_t _frameSize_type;
  _frameSize_type frameSize;

   typedef uint8_t _iframe_type;
  _iframe_type iframe;





  typedef boost::shared_ptr< ::pluto_camera_sense::frame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pluto_camera_sense::frame_<ContainerAllocator> const> ConstPtr;

}; // struct frame_

typedef ::pluto_camera_sense::frame_<std::allocator<void> > frame;

typedef boost::shared_ptr< ::pluto_camera_sense::frame > framePtr;
typedef boost::shared_ptr< ::pluto_camera_sense::frame const> frameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pluto_camera_sense::frame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pluto_camera_sense::frame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pluto_camera_sense

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'pluto_camera_sense': ['/home/cry2ra5y/my_catkin_workspace/src/pluto_camera_sense/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pluto_camera_sense::frame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pluto_camera_sense::frame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pluto_camera_sense::frame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pluto_camera_sense::frame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pluto_camera_sense::frame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pluto_camera_sense::frame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pluto_camera_sense::frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a745da853457763b31d9f94e2f97135";
  }

  static const char* value(const ::pluto_camera_sense::frame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a745da853457763ULL;
  static const uint64_t static_value2 = 0xb31d9f94e2f97135ULL;
};

template<class ContainerAllocator>
struct DataType< ::pluto_camera_sense::frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pluto_camera_sense/frame";
  }

  static const char* value(const ::pluto_camera_sense::frame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pluto_camera_sense::frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] frameBuffer\n"
"uint32 frameSize\n"
"bool iframe\n"
;
  }

  static const char* value(const ::pluto_camera_sense::frame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pluto_camera_sense::frame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frameBuffer);
      stream.next(m.frameSize);
      stream.next(m.iframe);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct frame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pluto_camera_sense::frame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pluto_camera_sense::frame_<ContainerAllocator>& v)
  {
    s << indent << "frameBuffer[]" << std::endl;
    for (size_t i = 0; i < v.frameBuffer.size(); ++i)
    {
      s << indent << "  frameBuffer[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.frameBuffer[i]);
    }
    s << indent << "frameSize: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frameSize);
    s << indent << "iframe: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.iframe);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUTO_CAMERA_SENSE_MESSAGE_FRAME_H
